export const ideas = [
    { id: 1, author_image: "images/get_idea_img.jpg", author_name: "Name1", idea_content: "Lorem ipsum dolor sit amet" },
    { id: 2, author_image: "images/get_idea_img.jpg", author_name: "Name2", idea_content: "Lorem ipsum dolor sit amet" },
    { id: 3, author_image: "images/get_idea_img.jpg", author_name: "Name3", idea_content: "Lorem ipsum dolor sit amet" },
    { id: 4, author_image: "images/get_idea_img.jpg", author_name: "Name4", idea_content: "Lorem ipsum dolor sit amet" },
    { id: 5, author_image: "images/get_idea_img.jpg", author_name: "Name5", idea_content: "Lorem ipsum dolor sit amet" },
    { id: 6, author_image: "images/get_idea_img.jpg", author_name: "Name6", idea_content: "Lorem ipsum dolor sit amet" },
    { id: 7, author_image: "images/get_idea_img.jpg", author_name: "Name7", idea_content: "Lorem ipsum dolor sit amet" },
    { id: 8, author_image: "images/get_idea_img.jpg", author_name: "Name8", idea_content: "Lorem ipsum dolor sit amet" },
    { id: 9, author_image: "images/get_idea_img.jpg", author_name: "Name9", idea_content: "Lorem ipsum dolor sit amet" },
    { id: 10, author_image: "images/get_idea_img.jpg", author_name: "Name10", idea_content: "Lorem ipsum dolor sit amet" },
    { id: 11, author_image: "images/get_idea_img.jpg", author_name: "Name11", idea_content: "Lorem ipsum dolor sit amet" },
    { id: 12, author_image: "images/get_idea_img.jpg", author_name: "Name12", idea_content: "Lorem ipsum dolor sit amet" },
    { id: 13, author_image: "images/get_idea_img.jpg", author_name: "Name13", idea_content: "Lorem ipsum dolor sit amet" },
    { id: 14, author_image: "images/get_idea_img.jpg", author_name: "Name14", idea_content: "Lorem ipsum dolor sit amet" },
    { id: 15, author_image: "images/get_idea_img.jpg", author_name: "Name15", idea_content: "Lorem ipsum dolor sit amet" },
    { id: 16, author_image: "images/get_idea_img.jpg", author_name: "Name16", idea_content: "Lorem ipsum dolor sit amet" },
    { id: 17, author_image: "images/get_idea_img.jpg", author_name: "Name17", idea_content: "Lorem ipsum dolor sit amet" },
    { id: 18, author_image: "images/get_idea_img.jpg", author_name: "Name18", idea_content: "Lorem ipsum dolor sit amet" },
    { id: 19, author_image: "images/get_idea_img.jpg", author_name: "Name19", idea_content: "Lorem ipsum dolor sit amet" },
    { id: 20, author_image: "images/get_idea_img.jpg", author_name: "Name20", idea_content: "Lorem ipsum dolor sit amet" },
    { id: 21, author_image: "images/get_idea_img.jpg", author_name: "Name21", idea_content: "Lorem ipsum dolor sit amet" },
    { id: 22, author_image: "images/get_idea_img.jpg", author_name: "Name22", idea_content: "Lorem ipsum dolor sit amet" },
    { id: 23, author_image: "images/get_idea_img.jpg", author_name: "Name23", idea_content: "Lorem ipsum dolor sit amet" },
    { id: 24, author_image: "images/get_idea_img.jpg", author_name: "Name24", idea_content: "Lorem ipsum dolor sit amet" },
    { id: 25, author_image: "images/get_idea_img.jpg", author_name: "Name25", idea_content: "Lorem ipsum dolor sit amet" },
];

